### ISSUE TITLE
Puli Factory is not available error.

### ISSUE THREAD

**Issue by irfanevrens** [mailgun/mailgun-php#116]
related 2.0

**Comment by matthendrix** [comment]
I get the same error. Additionally, the Puli Github page say this;

**ATTENTION: This package is not maintained anymore.**

**Comment by dirkpostma** [comment]
Any workaround known for this..?

**Comment by dirkpostma** [comment]
Workaround I use is setting the HTTP client explicitely, as documented in README.

```
    public function send($to, $body, $subject)
    {

		$client = new \Http\Adapter\Guzzle6\Client();
		$mg = new \Mailgun\Mailgun($this->key, $client);
		$domain = $this->domain;

		$mg->sendMessage($domain, array('from'    => 'info@example.com', 
		                                'to'      => $to, 
		                                'subject' => $subject, 
		                                'text'    => $body));

        return true;
    }

**Comment by bshaffer** [comment]
I following instructions in README and received this error as well.

**Comment by andrebellafronte** [comment]
same problem here

PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Puli Factory is not available'

The Puli Factory package has been abandoned 

https://packagist.org/packages/puli/factory
This package is abandoned and no longer maintained. No replacement package was suggested.

**Comment by yassine-ah** [comment]
+1

**Comment by cschalenborgh** [comment]
Any updates on this from Mailgun?

**Comment by cschalenborgh** [comment]
I got this response from their support team.

Per the recent update you now need to add a new line and change an old line when using the SDK. There are some instructions under the "Installation" portion of https://github.com/mailgun/mailgun-php that go into this in some detail, however here specifically are the lines:

```
New line:
$client = new \Http\Adapter\Guzzle6\Client();

Changed line:
Used to be:
$mgClient = new Mailgun('key-goes-here');

Now is:
$mailgun = new \Mailgun\Mailgun('api_key', $client);

Also, please make sure the variable you are calling in the send function now includes $mailgun instead of $mgClient.
```

Here is an example on how sending a basic message looks like now with the recent update:

```
<?php
# Include the Autoloader (see "Libraries" for install instructions)
require 'vendor/autoload.php';
use Mailgun\Mailgun;

$client = new \Http\Adapter\Guzzle6\Client();
$mailgun = new \Mailgun\Mailgun('api_key', $client);

# Instantiate the client.
$domain = "domain.com";

# Make the call to the client.
$result = $mailgun->sendMessage($domain, array(
    'from'    => 'Excited User <mailgun@domain.com>',
    'to'      => 'Baz <you@gmail.com>',
    'subject' => 'Hello',
    'text'    => 'Testing some Mailgun awesomness!'));

$id = $result->http_response_body->id;
echo $id

?>
```

Hope this helps..

**Comment by dtruel** [comment]
Doesn't work for me - even with the fix above I get

```
Catchable fatal error: Argument 1 passed to Http\Adapter\Guzzle6\Client::buildClient() must be of the type array, none given, called in /home/shatgame/public_html/cybersecuritybook.net/vendor/php-http/guzzle6-adapter/src/Client.php on line 31 and defined in /home/shatgame/public_html/cybersecuritybook.net/vendor/php-http/guzzle6-adapter/src/Client.php on line 76
```

**Comment by undefinedor** [comment]
I get the same error. How to solve it..

**Comment by bshaffer** [comment]
I fixed it by explicitly setting the adapter in `composer.json`:

```
composer require "php-http/guzzle6-adapter: ^1.0"
```

**Comment by undefinedor** [comment]
Yeah~ Thank you ..

**Comment by d4rkd0s** [comment]
Hmm didn't work for me still getting this,
```
2016-05-15 13:19:31: (mod_fastcgi.c.2673) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Puli Factory is not available' in /var/www/vendor/php-http/discovery/src/ClassDiscovery.php:32
2016-05-15 13:19:31: (mod_fastcgi.c.2673) FastCGI-stderr: Stack trace:
2016-05-15 13:19:31: (mod_fastcgi.c.2673) FastCGI-stderr: #0 /var/www/vendor/php-http/discovery/src/ClassDiscovery.php(79): Http\Discovery\ClassDiscovery::getPuliFactory()
2016-05-15 13:19:31: (mod_fastcgi.c.2673) FastCGI-stderr: #1 /var/www/vendor/php-http/discovery/src/ClassDiscovery.php(99): Http\Discovery\ClassDiscovery::getPuliDiscovery()
2016-05-15 13:19:31: (mod_fastcgi.c.2673) FastCGI-stderr: #2 /var/www/vendor/php-http/discovery/src/HttpClientDiscovery.php(21): Http\Discovery\ClassDiscovery::findOneByType('Http\Client\Htt...')
2016-05-15 13:19:31: (mod_fastcgi.c.2673) FastCGI-stderr: #3 /var/www/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(270): Http\Discovery\HttpClientDiscovery::find()
2016-05-15 13:19:31: (mod_fastcgi.c.2673) FastCGI-stderr: #4 /var/www/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(87): Mailgun\Connection\RestClient->getHttpClient()
2016-05-15 13:19:31: (mod_fastcgi.c.2673) FastCGI-stderr: #5 /var/www/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(138): Mailgun\Connection\RestClient->send('POST', 'mg.website.com...', Array, Array)
2016-05-15 13:19:31: (mod_fastcgi.c.2673) FastCGI-stderr: #6 /var/www/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(110): Mailgun\C in /var/www/vendor/php-http/discovery/src/ClassDiscovery.php on line 32
```

**Comment by carlituxman** [comment]
With this works:

$client = new \Http\Adapter\Guzzle6\Client(); $mailgun = new \Mailgun\Mailgun('api_key', $client);

**Comment by shahidbasheer** [comment]
composer require "php-http/guzzle6-adapter: ^1.0"
" Could not find package ^1.0 at any version for your minimum-stability (stab
  le). Check the package spelling or your minimum-stability
"

i solved by versin ^1.1
composer require php-http/guzzle6-adapter

**Comment by Nyholm** [comment]
This PR will fix the issue as it updates php-http/discovery to 1.0. That version does no longer require Puli

https://github.com/mailgun/mailgun-php/pull/139/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R8

**Comment by Nyholm** [comment]
This issue is fixed in 2.1

**Comment by TrogWarZ** [comment]
Same here.

`composer.json`:
```json
    "require"     : {
        "php"                      : "^5.6",
        "mailgun/mailgun-php"      : "^2.1",
        "guzzlehttp/guzzle"        : "^6.2",
        "php-http/guzzle6-adapter" : "^1.1"
    }
```

Code:
```php
$options = [
    'from'    => 'test@mailgun.com',
    'to'      => 'Foobar <foobar@example.com>',
    'subject' => 'Test MG',
    'text'    => 'Sup, man',
    'o:tag'   => 'test,mailgun,sup,hello',
];
$client = new \Mailgun\Mailgun('s0m3s3c93t4P1K3Y', new \Http\Adapter\Guzzle6\Client());
$client->sendMessage($this->apiDomain, $options);
```

Email was **really sent**, but i see exception:
```
Http\Discovery\Exception\PuliUnavailableException: Puli Factory is not available in /var/www/acme/development/shared/vendor/php-http/discovery/src/Strategy/PuliBetaStrategy.php on line 39

Call Stack:
    0.0001     237160   1. 
    0.0043     833656   2. 
    0.0186     870392   3. 
    0.0192     970408   4. 
    0.0192     971344   5. 
    0.0222    1127232   6. Mails->send() /var/www/acme/development/releases/current/controllers/Controller_Ajax.php:2131
    0.0223    1130000   7. Mailgun\Mailgun->sendMessage(string(51), array(5), array(0)) /var/www/acme/development/releases/current/extensions/Mails.php:250
    0.0224    1130176   8. Mailgun\Mailgun->post(string(60), array(5), array(0)) /var/www/acme/development/shared/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php:61
    0.0224    1130248   9. Mailgun\Connection\RestClient->post(string(60), array(5), array(0)) /var/www/acme/development/shared/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php:118
    0.0224    1137920  10. Mailgun\Connection\RestClient->send(string(4), string(60), array(0), array(8), ???) /var/www/acme/development/shared/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:151
    0.0226    1146632  11. Http\Message\MultipartStream\MultipartStreamBuilder->__construct(???) /var/www/acme/development/shared/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:85
    0.0227    1157624  12. Http\Discovery\StreamFactoryDiscovery::find() /var/www/acme/development/shared/vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php:43
    0.0227    1157784  13. Http\Discovery\ClassDiscovery::findOneByType(string(26)) /var/www/acme/development/shared/vendor/php-http/discovery/src/StreamFactoryDiscovery.php:25
    0.0227    1158200  14. call_user_func:{/var/www/acme/development/shared/vendor/php-http/discovery/src/ClassDiscovery.php:54}(string(55), string(26)) /var/www/acme/development/shared/vendor/php-http/discovery/src/ClassDiscovery.php:54
    0.0228    1162432  15. Http\Discovery\Strategy\PuliBetaStrategy::getCandidates(string(26)) /var/www/acme/development/shared/vendor/php-http/discovery/src/ClassDiscovery.php:54
    0.0228    1162680  16. Http\Discovery\Strategy\PuliBetaStrategy::getPuliDiscovery() /var/www/acme/development/shared/vendor/php-http/discovery/src/Strategy/PuliBetaStrategy.php:79
    0.0228    1162784  17. Http\Discovery\Strategy\PuliBetaStrategy::getPuliFactory() /var/www/acme/development/shared/vendor/php-http/discovery/src/Strategy/PuliBetaStrategy.php:64
```

What i'm doing wrong?

**Comment by jasonmccreary** [comment]
Received the same issue, Google led me here, installed mailgun-php version 2.1.2...

**Comment by Nyholm** [comment]
Have a look at the documentation for Httplug: http://docs.php-http.org/en/latest/discovery.html#puli-factory-is-not-available

Also, Are you running php-http/discovery > 1.0? 
Have you installed the message factories? php-http/message
Have you installed a client? php-http/curl-client 
Have you installed a PSR7 implementation? guzzlehttp/psr7

**Comment by jasonmccreary** [comment]
> Also, Are you running php-http/discovery > 1.0? 

Yes. Version 1.1.

> Have you installed a client?

Yes, I installed `php-http/guzzle6-adapter` and adjusted the code per the comments above to get it working.

I think it was just unclear from the comments here, docs, and common `composer install` practices what I needed to do to get it working.

**Comment by debojyoti** [comment]
Total 3 packages are required to run it properly
**mailgun/mailgun-php, 
php-http/curl-client, 
guzzlehttp/psr7**

So in your composer.json add
```json
"mailgun/mailgun-php": "dev-master",
"php-http/curl-client": "dev-master",
"guzzlehttp/psr7": "dev-master"
```

**Comment by LawSikho** [comment]
> Total 3 packages are required to run it properly

Thanks it worked. But why dev-master? In my case it worked with the latest versions.

**Comment by DavidGarciaCat** [comment]
Hey @debojyoti 

That's not true , you can read on our [README](https://github.com/mailgun/mailgun-php#why-requiring-so-many-packages) file that we rely on virtual packages, so you are not "forced" to use the ones that you have listed there, they are just a suggestion but you are free to choose the ones that you want.

Hey @LawSikho 

Obviously, for stable development, the recommendation is to use always stable versions, but never `dev-maser` - this one must be always your last option due `dev-master` might contain non-stable code (depending on the project) or code that might be removed before the next release.

**Comment by amitdude69** [comment]
hi
