### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by mackenziexD** [mailgun/mailgun-php#180]
any ideas? 

<b>Fatal error</b>:  Uncaught exception 'Http\Discovery\Exception\PuliUnavailableException' with message 'Puli Factory is not available' in C:\xampp\htdocs\CMS\vendor\php-http\discovery\src\Strategy\PuliBetaStrategy.php:39

Stack trace:
#0 C:\xampp\htdocs\CMS\vendor\php-http\discovery\src\Strategy\PuliBetaStrategy.php(64): Http\Discovery\Strategy\PuliBetaStrategy::getPuliFactory()
#1 C:\xampp\htdocs\CMS\vendor\php-http\discovery\src\Strategy\PuliBetaStrategy.php(79): Http\Discovery\Strategy\PuliBetaStrategy::getPuliDiscovery()
#2 [internal function]: Http\Discovery\Strategy\PuliBetaStrategy::getCandidates('Http\Message\Me...')
#3 C:\xampp\htdocs\CMS\vendor\php-http\discovery\src\ClassDiscovery.php(54): call_user_func('Http\Discovery\...', 'Http\Message\Me...')
#4 C:\xampp\htdocs\CMS\vendor\php-http\discovery\src\MessageFactoryDiscovery.php(25): Http\Discovery\ClassDiscovery::findOneByType('Http\Message\Me...')
#5 C:\xampp\htdocs\CMS\vendor\mailgun\mailgun-php\src\Mailgun\Connection\RestClient.php(104): Http\Discovery\Messa in <b>C:\xampp\htdocs\CMS\vendor\php-http\discovery\src\MessageFactoryDiscovery.php</b> on line <b>27</b><br />

**Comment by Nyholm** [comment]
Have a look here: http://docs.php-http.org/en/latest/discovery.html#strategies and here: http://docs.php-http.org/en/latest/discovery.html#puli-factory-is-not-available

Are you running the latest version of this library and version 1.0 of php-http/discovery?

**Comment by Nyholm** [comment]
Im closing this because of inactivity.
