### ISSUE TITLE
The parameters passed to the API were invalid. Check your inputs!

### ISSUE THREAD

**Issue by ArsenBespalov** [mailgun/mailgun-php#261]
**After send 2 mail, show this error:**

```
The parameters passed to the API were invalid. Check your inputs!

#0 /home/lead-dev/phalcon/www/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(70): Mailgun\Connection\RestClient->responseHandler(Object(Guzzle\Http\Message\Response))
#1 /home/lead-dev/phalcon/www/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(60): Mailgun\Connection\RestClient->post('mg.lead4crm.ru/...', Array, Array)
#2 /home/lead-dev/phalcon/www/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(38): Mailgun\Mailgun->post('mg.lead4crm.ru/...', Array, Array)
#3 /home/lead-dev/phalcon/www/apps/cabinet/controllers/RegisterController.php(40): Mailgun\Mailgun->sendMessage('mg.lead4crm.ru', Array)
#4 [internal function]: Lead\Cabinet\Controllers\RegisterController->testAction()
#5 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(Lead\Cabinet\Controllers\RegisterController), 'testAction', Array)
#6 [internal function]: Phalcon\Dispatcher->_dispatch()
#7 [internal function]: Phalcon\Dispatcher->dispatch()
#8 /home/lead-dev/phalcon/www/public/index.php(88): Phalcon\Mvc\Application->handle()
#9 {main}
```

I use this code:
```
use Mailgun\Mailgun;

$mg = new Mailgun('apikey-domain');
$mg->sendMessage('my-domain', [
    'from' => 'Test <no-reply@my-domain>',
    'to' => 'any@mail.domain',
    'subject' => 'Test',
    'text' => 'Message text',
]);
```

**Comment by DavidGarciaCat** [comment]
Hello @ArsenBespalov

What Mailgun SDK version are you using?

Thanks,

**Comment by ArsenBespalov** [comment]
Hi, @DavidGarciaCat!

I use old version, after update it's correctly work.

Thanks.
