### ISSUE TITLE
Renaming attachments not working

### ISSUE THREAD

**Issue by Bogardo** [mailgun/mailgun-php#35]
I haven't been able to send attachments using the new method to rename the attachments.

Here is the test code I used:

``` php
# Include the Autoloader (see "Libraries" for install instructions)
require 'vendor/autoload.php';
use Mailgun\Mailgun;

# Instantiate the client.
$mgClient = new Mailgun('my-key');
$domain = "my-domain";

# Make the call to the client.

try {
    //Version 1 | from docs (old)
    $result = $mgClient->sendMessage("$domain",
        array(
            'from'    => 'Excited User <me@samples.mailgun.org>',
            'to'      => 'foo@bar.com',
            'subject' => 'Version 1 | from docs (old)',
            'text'    => 'Testing some Mailgun awesomness!',
            'html'    => '<html>HTML version of the body</html>'
        ),
        array(
            'attachment' => array(
                '@C:\Projects\Sandbox\mailgun\testfile_1.txt',
                '@C:\Projects\Sandbox\mailgun\testfile_2.txt'
            )
        )
    );
} catch (Exception $e) {
    var_dump($e->getMessage());
}

try {
    // Version 2 | New version with attachment renaming (without 'attachment' key)
    $result = $mgClient->sendMessage("$domain",
        array(
            'from'    => 'Excited User <me@samples.mailgun.org>',
            'to'      => 'foo@bar.com',
            'subject' => "Version 2 | New version with attachment renaming (without 'attachmnt' key)",
            'text'    => 'Testing some Mailgun awesomness!',
            'html'    => '<html>HTML version of the body</html>'
        ),
        array(
            array(
                'filePath' => '@C:\Projects\Sandbox\mailgun\testfile_1.txt',
                'remoteName' => 'NumberOne.txt'
            ),
            array(
                'filePath'   => '@C:\Projects\Sandbox\mailgun\testfile_2.txt', 
                'remoteName' => 'NumberTwo.txt'
            )
        )
    );
} catch (Exception $e) {
    var_dump($e->getMessage());
}

try {
    //Version 3 | New version with attachment renaming (with 'attachment' key) 
    $result = $mgClient->sendMessage("$domain",
        array(
            'from'    => 'Excited User <me@samples.mailgun.org>',
            'to'      => 'foo@bar.com',
            'subject' => "Version 3 | New version with attachment renaming (with 'attachment' key)",
            'text'    => 'Testing some Mailgun awesomness!',
            'html'    => '<html>HTML version of the body</html>'
        ),
        array(
            'attachment' => array(
                'filePath' => '@C:\Projects\Sandbox\mailgun\testfile_1.txt',
                'remoteName' => 'NumberOne.txt'
            ),
            'attachment' => array(
                'filePath'   => '@C:\Projects\Sandbox\mailgun\testfile_2.txt', 
                'remoteName' => 'NumberTwo.txt'
            )
        )
    );
} catch (Exception $e) {
    var_dump($e->getMessage());
}
```

After running the above I only receive the first two emails.
Here are the results per version/mail:
- Version 1: No problems, email arrives with the two attachments
- Version 2: Email arrives without attachments
- Version 3: Throws exception "Unable to open NumberTwo.txt for reading" (see below)

```
Fatal error: Uncaught exception 'Guzzle\Common\Exception\InvalidArgumentException' with message 'Unable to open NumberTwo.txt for reading' in C:\Projects\Sandbox\mailgun\vendor\guzzle\guzzle\src\Guzzle\Http\Message\PostFile.php:53 
Stack trace: 
#0 C:\Projects\Sandbox\mailgun\vendor\guzzle\guzzle\src\Guzzle\Http\Message\PostFile.php(28): Guzzle\Http\Message\PostFile->setFilename('NumberTwo.txt') 
#1 C:\Projects\Sandbox\mailgun\vendor\guzzle\guzzle\src\Guzzle\Http\Message\EntityEnclosingRequest.php(199): Guzzle\Http\Message\PostFile->__construct('attachment', 'NumberTwo.txt', NULL, NULL) 
#2 C:\Projects\Sandbox\mailgun\vendor\mailgun\mailgun-php\src\Mailgun\Connection\RestClient.php(55): Guzzle\Http\Message\EntityEnclosingRequest->addPostFile('attachment', 'NumberTwo.txt') 
#3 C:\Projects\Sandbox\mailgun\vendor\mailgun\mailgun-php\src\Mailgun\Mailgun.php(60): Mailgun\Connection\RestClient->post('******/...', Array, Array) 
#4 C:\Projects\Sandbox\mailgun\vendor\mailgun\mailgun-php\src\Mailgun\Mailgun.php(38): Mailgun\Mail in C:\Projects\Sandbox\mailgun\vendor\guzzle\guzzle\src\Guzzle\Http\Message\PostFile.php on line 53
```

**Comment by kushalappamp** [comment]
using the same code for attachments, 

i am getting error lik
Caught exception: Unable to open \uploads\file.txt for reading

array('attachment' => array(
                                    array('filePath'   => '@\uploads\file.txt', 
                                          'remoteName' => 'file.txt'),
