### ISSUE TITLE
Fatal error: Uncaught Mailgun\Exception\HttpClientException: The parameters passed to the API were invalid. Check your inputs! 

### ISSUE THREAD

**Issue by mbadaone** [mailgun/mailgun-php#462]
after following the instructions and running i am getting the following error 

Fatal error: Uncaught Mailgun\Exception\HttpClientException: The parameters passed to the API were invalid. Check your inputs! in my-drive-path\mailgun\v2.0\vendor\mailgun\mailgun-php\src\Mailgun\Exception\HttpClientException.php:58 Stack trace: #0 my-drive-path\mailgun\v2.0\vendor\mailgun\mailgun-php\src\Mailgun\Api\HttpApi.php(91): Mailgun\Exception\HttpClientException::badRequest(Object(GuzzleHttp\Psr7\Response)) #1 my-drive-path\mailgun\v2.0\vendor\mailgun\mailgun-php\src\Mailgun\Api\HttpApi.php(73): Mailgun\Api\HttpApi->handleErrors(Object(GuzzleHttp\Psr7\Response)) #2 my-drive-path\mailgun\v2.0\vendor\mailgun\mailgun-php\src\Mailgun\Api\Message.php(52): Mailgun\Api\HttpApi->hydrateResponse(Object(GuzzleHttp\Psr7\Response), 'Mailgun\\Model\\M...') #3 my-drive-path\mailgun\v2.0\index.php(12): Mailgun\Api\Message->send('mailgun.gap365....', Array) #4 {main} thrown in my-drive-path\mailgun\v2.0\vendor\mailgun\mailgun-php\src\Mailgun\Exception\HttpClientException.php on line 58

**Comment by DavidGarciaCat** [comment]
Hi @mbadaone 

I have just run a test following the steps on our [README](https://github.com/mailgun/mailgun-php#installation) and I was able to send a message.

What is your operating system? Did you miss maybe one or more packages? Please note we don't expect to get `mailgun` as the only required package when installing this vendor.

Cheers,

**Comment by DigitalSolo** [comment]
I'm getting the same error.  My problem is that I know I'm passing an invalid email address but I'm doing a batch and have no idea what the bad email address is.  The error message should give some detail about what WAS passed to the api.

**Comment by Nyholm** [comment]
What version are you running? Did you test with dev-master?
