### ISSUE TITLE
Can't add users to mailgun mailing lists

### ISSUE THREAD

**Issue by setkyar** [mailgun/mailgun-php#49]
I try like the following that I was saw at the doc.

```
<?php
# Include the Autoloader (see "Libraries" for install instructions)
require 'vendor/autoload.php';
use Mailgun\Mailgun;

# Instantiate the client.
$mgClient = new Mailgun('key-3ax6xnjp29jd6fds4gc373sgvjxteol0');
$listAddress = 'dev@samples.mailgun.org';

# Issue the call to the client.
$result = $mgClient->post("lists/$listAddress/members", array(
    'address'     => 'bar@example.com',
    'name'        => 'Bob Bar',
    'description' => 'Developer',
    'subscribed'  => true,
    'vars'        => '{"age": 26}'
));
```

But I got the following errors 

```
127.0.0.1:46067 [500]: /addmailinglist.php - Uncaught exception 'Mailgun\Connection\Exceptions\MissingRequiredParameters' with message 'The parameters passed to the API were invalid. Check your inputs!' in /mailgun/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:125
Stack trace:
#0 mailgun/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(90): Mailgun\Connection\RestClient->responseHandler(Object(Guzzle\Http\Message\Response))
#1 /mailgun/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(56): Mailgun\Connection\RestClient->post('lists/dev@sampl...', Array, Array)
#2 /mailgun/addmailinglist.php(17): Mailgun\Mailgun->post('lists/dev@sampl...', Array)
#3 {main}
  thrown in /mailgun/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 125
```

When I tracke the errors, I know I miss two parameter. So add and test with empty paramater but I still got and errors.

**Comment by Nyholm** [comment]
Is this still an issue in the latest version?

**Comment by Nyholm** [comment]
Closing because of inactivity.
