### ISSUE TITLE
Error on installation - missing dependency?

### ISSUE THREAD

**Issue by enygma** [mailgun/mailgun-php#493]
In using the install command listed in the `README`:

```
composer require mailgun/mailgun-php php-http/curl-client guzzlehttp/psr7
```

And the following code:

```php
<?php
$mg = new \Mailgun\Mailgun($_ENV['MAILGUN_SECRET_KEY']);
$domain = $_ENV['MAILGUN_DOMAIN'];

return $mg->sendMessage($domain, $data);
```

I get the following error - it looks like a missing package or something: 

`Class Nyholm\Psr7\Request not found.` 

Is there a dependency I'm missing somewhere?

**Comment by enygma** [comment]
Hmm, I tried the method from the Usage section and I'm still getting the same error about `Nyholm\Psr7\Request`. I've included the stack trace I'm getting below:

```
#0 [internal function]: {closure}('Nyholm\\Psr7\\Req...')
#1 [internal function]: spl_autoload_call('Nyholm\\Psr7\\Req...')
#2 /var/www/html/vendor/php-http/discovery/src/ClassDiscovery.php(165): is_callable(Array)
#3 /var/www/html/vendor/php-http/discovery/src/ClassDiscovery.php(63): Http\Discovery\ClassDiscovery::evaluateCondition(Array)
#4 /var/www/html/vendor/php-http/discovery/src/UriFactoryDiscovery.php(25): Http\Discovery\ClassDiscovery::findOneByType('Http\\Message\\Ur...')
#5 /var/www/html/vendor/mailgun/mailgun-php/src/Mailgun/HttpClientConfigurator.php(136): Http\Discovery\UriFactoryDiscovery::find()
#6 /var/www/html/vendor/mailgun/mailgun-php/src/Mailgun/HttpClientConfigurator.php(71): Mailgun\HttpClientConfigurator->getUriFactory()
#7 /var/www/html/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(100): Mailgun\HttpClientConfigurator->createConfiguredClient()
#8 /var/www/html/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(114): Mailgun\Mailgun::configure(Object(Mailgun\HttpClientConfigurator))
#9 /var/www/html/App/Provider/Email.php(35): Mailgun\Mailgun::create('<key here>')
#10 /var/www/html/App/Controller/UserController.php(124): App\Provider\Email::send(Object(App\Mail\User\Register))
```

**Comment by enygma** [comment]
So I did like you did and made the completely different script to test and, yes, it did work fine. So now I'm even more confused. Why would it be selecting the `Nyholm` package instead of trying to use the cURL client? Maybe it's a package conflict somewhere? Here's my `composer.json`:

```
{
    "require": {
        "slim/slim": "^3.10",
        "slim/twig-view": "^2.4",
        "psecio/validation": "^0.5.4",
        "aura/session": "^2.1",
        "vlucas/phpdotenv": "^2.5",
        "illuminate/database": "^5.7",
        "robmorgan/phinx": "^0.10.6",
        "doctrine/dbal": "^2.8",
        "erusev/parsedown": "^1.7",
        "psecio/propauth": "^1.1",
        "mailgun/mailgun-php": "^2.6",
        "php-http/curl-client": "^1.7",
        "guzzlehttp/psr7": "^1.4"
    }
}
```

See anything that might cause issues?

**Comment by enygma** [comment]
I got it...the issue was in a custom autoloader I have in place. So in the client code (or one of the dependencies), I bet there's an `is_callable` call somewhere. Because of how PHP works, this actually invokes the autoloader to see if it can include the related file(s). 

In my autoloader, however, I was throwing an exception when the class/files weren't found. In this case, since the `Nyholm\Psr7\Request` isn't present, the autoloader threw the exception and the script bombed out.

I guess I'll change my autoloader to only log when a class isn't found but it seems like it might be worth a note in the documentation somewhere to those making custom autoloaders so they don't bump against this themselves and get confused. I'm going to close this one out - thanks for the assistance!
