### ISSUE TITLE
GoDaddy error setting certificate verify location

### ISSUE THREAD

**Issue by bendirectory** [mailgun/mailgun-php#502]
I'm calling mailgun to send a message through a PHP page on GoDaddy windows hosting.  I just started over with a fresh install of the latest of mailgun-php by following the installation instructions.  Now I'm getting this error message.  The highest version of PHP I can have on GoDaddy windows hosting is 5.6.  I've been searching for several hours, and have not been able to find an answer.  Below the error message is my code.

[15-Dec-2018 10:36:22 America/Phoenix] PHP Fatal error:  Uncaught exception 'Http\Client\Exception\RequestException' with message 'error setting certificate verify locations:
  CAfile: c:\cgi\php56\curl-ca-bundle.crt
  CApath: none' in D:\Hosting\redacted\mailgun-php\vendor\php-http\curl-client\src\Client.php:137
Stack trace:
#0 D:\Hosting\redacted\mailgun-php\vendor\mailgun\mailgun-php\src\Mailgun\Connection\RestClient.php(108): Http\Client\Curl\Client->sendRequest(Object(GuzzleHttp\Psr7\Request))
#1 D:\Hosting\redacted\mailgun-php\vendor\mailgun\mailgun-php\src\Mailgun\Connection\RestClient.php(179): Mailgun\Connection\RestClient->send('POST', '<domain>...', Array, Array)
#2 D:\Hosting\redacted\mailgun-php\vendor\mailgun\mailgun-php\src\Mailgun\Mailgun.php(204): Mailgun\Connection\RestClient->post('<domain>..', Array, Array)
#3 D:\Hosting\redacted\mailgun-php\sendmail.php(66): Mail in D:\Hosting\redacted\mailgun-php\vendor\php-http\curl-client\src\Client.php on line 137

```
<?php
error_reporting(E_ALL);
ini_set ('log_errors', 'on');
ini_set ('display_startup_errors', 'on');
ini_set ('error_reporting', E_ALL);
ini_set('error_log','D:\Hosting\redacted\html\phplogs\php_errors.log');

require 'vendor/autoload.php';
use Mailgun\Mailgun;

if(strtoupper($_SERVER['REQUEST_METHOD']) != 'POST')
	die('Invalid Mail Send request - rejected');

$message = htmlspecialchars($_POST['message']);
$subject = htmlspecialchars($_POST['subject']);
$attachments = json_decode($_POST['attachments']);
$toName = htmlspecialchars($_POST['toName']);
$toAddress = htmlspecialchars($_POST['toAddress']);
$emailTag = htmlspecialchars($_POST['email_tag']);
$from = "Site.com <quote@site.com>";
$domain = "<domain>";

error_log('>>>>>> ' . $emailTag);


// setup credentials
$mg = new Mailgun("key");

# Next, instantiate a Message Builder object from the SDK.
$msgBldr = $mg->MessageBuilder();
# Define the from address.
$msgBldr->setFromAddress($from);
# Define a to recipient.
$msgBldr->addToRecipient($toAddress);
#Define bcc for maintenance
$msgBldr->addBccRecipient('dev@dev.com');
# Define the subject.
$msgBldr->setSubject($subject);
# Define the body of the message.
$msgBldr->setTextBody($message);

$tempfiles = array();
# Add attachments
error_log("Attachment Count: " . strval(count($attachments)));
foreach ($attachments as $key => $value){

	$temp_file = tempnam(sys_get_temp_dir(), $value->name);
	file_put_contents($temp_file, base64_decode($value->content));
	$attSuccess = $msgBldr->addAttachment($temp_file, $value->name);
	$tempfiles[] = $temp_file;
}

$msg = $msgBldr->getMessage();
error_log("Message to send: " . json_encode($msg));

$files = $msgBldr->getFiles();
error_log("Sending files: " . json_encode($files));

$postAddr = "$domain/messages";
error_log("PostTo: " . $postAddr);

# Finally, send the message.
$mg->post($postAddr, $msg, $files);

// clean up temp files
foreach($tempfiles as $key => $f_name){
	unlink($f_name);
}

?>

```

**Comment by DavidGarciaCat** [comment]
Hi @bendirectory

The first problem I can see here is `Windows` 😄 - Is well known that PHP gives support for Windows, but also that Windows is usually throwing internal errors when we run PHP code that just works on Linux or Mac environments.

The second problem I can see is the certificates, due to Mailgun works through a mix of API Key and Domain, but not a certificate (at least on their basic plan), so I am not sure how this can be related to Mailgun SDK. If certificates are required for premium plans then is something beyond my knowledge, unfortunately, because I never needed to consider upgrades to cover all my needs.

The third problem I can see is that the thrown exception `Http\Client\Exception\RequestException` is not part of Mailgun's namespace, so it seems an error triggered by the HTTP Client that you're trying to use and although this client is called through Mailgun files, the client is a `vendor`, not a built-in library included in this SDK.

The fourth problem I can see is that you're not following the recommended steps (included in the [`Readme`](https://github.com/mailgun/mailgun-php/blob/master/README.md#usage) file) to set-up the Mailgun SDK or to send messages, looks like you're using the old approach that is flagged as deprecated and was replaced by a new one.

Due to all of this, I would suggest to review how you're instantiating your Milgun client, following the recommended steps, and the piece of code that you're using to send the emails.

Cheers,
