### ISSUE TITLE
guzzlehttp undefined function

### ISSUE THREAD

**Issue by NYCJacob** [mailgun/mailgun-php#608]
I am getting a 500 error on calls to my mail script although the message is being sent.  In my apache error log I see
PHP Fatal error:
Uncaught Error: Call to undefined function GuzzleHttp\\Psr7\\filter_var()

I am using autoloading. Wondering if anyone else has seen this/solutions?

**Comment by DavidGarciaCat** [comment]
Hi @NYCJacob 

Thanks for posting the issue

Would it be possible getting the full backtrace of the error? As per my initial reading of your issue, it looks to me like the problem is not part of the SDK - given the message is sent - but on the Guzzle integration. Getting the steps to reproduce the error and the backtrace that you're getting to compare might be helpful.

Cheers!

**Comment by NYCJacob** [comment]
so I don't get error on my local machine and my stack trace using the remote to a mess of javascript files created by React.  This is what I see in the apache error log:
PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\\Psr7\\filter_var() in /usr/local/www/apache24/data/marbletownstrong/vendor/guzzlehttp/psr7/src/Response.php:96\nStack trace:\n#0 /usr/local/www/apache24/data/marbletownstrong/vendor/guzzlehttp/guzzle/src/Handler/EasyHandle.php(81): GuzzleHttp\\Psr7\\Response->__construct('200', Array, Object(GuzzleHttp\\Psr7\\Stream), '1.1', 'OK')\n#1 /usr/local/www/apache24/data/marbletownstrong/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(545): GuzzleHttp\\Handler\\EasyHandle->createResponse()\n#2 [internal function]: GuzzleHttp\\Handler\\CurlFactory->GuzzleHttp\\Handler\\{closure}(Resource id #104, '\\r\\n')\n#3 /usr/local/www/apache24/data/marbletownstrong/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(108): curl_multi_exec(Resource id #107, 0)\n#4 /usr/local/www/apache24/data/marbletownstrong/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(125): GuzzleHttp\\Handler\\CurlMultiHandler->tick()\n#5 /usr/local/www/apache24/data/marbletownstrong/vendor/guzzlehttp/pro in /usr/local/www/apache24/data/marbletownstrong/vendor/guzzlehttp/psr7/src/Response.php on line 96, referer: http://marbletownstrong.com/
