### ISSUE TITLE
Class 'HttpClientConfigurator' not found

### ISSUE THREAD

**Issue by musmanzpak** [mailgun/mailgun-php#647]
Please guide my code is:

```php
require 'vendor/autoload.php';
use Mailgun\Mailgun;

$configurator = new HttpClientConfigurator();
$configurator->setEndpoint('http://bin.mailgun.net/07051324');
$configurator->setDebug(true);
$mg = new Mailgun($configurator);

$mg = Mailgun::create('key-example', 'https://api.eu.mailgun.net'); // For EU servers

// Now, compose and send your message.
// $mg->messages()->send($domain, $params);
$mg->messages()->send('example.com', [
  'from'    => 'mailgun@example.com',
  'to'      => 'example@gmail.com',
  'subject' => 'The PHP SDK is awesome!',
  'text'    => 'It is so simple to send a message.'
]);
```

**Comment by mstroink** [comment]
Check that you're importing the class at the top.

`use Mailgun\HttpClient\HttpClientConfigurator;`

**Comment by Nereg** [comment]
Tryed code with you edit and got many more errors : 
```
PHP Fatal error:  Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors
 - Puli Factory is not available
 - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: .
 - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: Nyholm\Psr7\Factory\Psr17Factory, Zend\Diactoros\UriFactory, Http\Factory\Diactoros\UriFactory, Http\Factory\Guzzle\UriFactory, Http\Factory\Slim\UriFactory.

 in /apps/main/vendor/php-http/discovery/src/Exception/DiscoveryFailedException.php:41
Stack trace:
#0 /apps/main/vendor/php-http/discovery/src/ClassDiscovery.php(79): Http\Discovery\Exception\DiscoveryFailedException::create(Array)
#1 /apps/main/vendor/php-http/discovery/src/Psr17FactoryDiscovery.php(117): Http\Discovery\ClassDiscovery::findOneByType('Psr\\Http\\ in /apps/main/vendor/php-http/discovery/src/Psr17FactoryDiscovery.php on line 22

Fatal error: Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors
 - Puli Factory is not available
 - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: .
 - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: Nyholm\Psr7\Factory\Psr17Factory, Zend\Diactoros\UriFactory, Http\Factory\Diactoros\UriFactory, Http\Factory\Guzzle\UriFactory, Http\Factory\Slim\UriFactory.

 in /apps/main/vendor/php-http/discovery/src/Exception/DiscoveryFailedException.php:41
Stack trace:
#0 /apps/main/vendor/php-http/discovery/src/ClassDiscovery.php(79): Http\Discovery\Exception\DiscoveryFailedException::create(Array)
#1 /apps/main/vendor/php-http/discovery/src/Psr17FactoryDiscovery.php(117): Http\Discovery\ClassDiscovery::findOneByType('Psr\\Http\\ in /apps/main/vendor/php-http/discovery/src/Psr17FactoryDiscovery.php on line 22
```

**Comment by cjrasmussen** [comment]
Old issue but I just ran into this myself.  Turned out it was because I'd only required mailgun/mailgun-php, not kriswallsmith/buzz and/or nyholm/psr7.

Seems to me like those two should be requirements of mailgun/mailgun-php via its composer.json, rather than requiring them separately, but I don't know if there's some reason not to do that.

**Comment by DavidGarciaCat** [comment]
The reason is that Mailgun SDK **does not require** a specific implementation, as the SDK provides an open functionality thanks to the HttPlug implementations, so no matter if you use Buzz, Guzzle or another client as well as PSR7 implementation.

Moreover, the `composer.json` file **suggests** these two packages, but you are free to use any implementation that you consider it fits better t your project and your needs

https://github.com/mailgun/mailgun-php/blob/4acac804bf64bbfa86305afc6a53c28201154b39/composer.json#L28-L31

Cheers,
