### ISSUE TITLE
Fatal error when requiring TLS

### ISSUE THREAD

**Issue by truefusion** [mailgun/mailgun-php#735]
Not sure how to resolve.

Code used to create the error:
```php
$mg = Mailgun::create(MailGunKey);

$mg->messages()->send(MailgunDomain, [
	'from' => From,
	'to' => To,
	'subject' => 'Test',
	'html' => 'Hello world',
	'o:require-tls' => true,
]);
```

Resulting error:
```
Fatal error:  Uncaught TypeError: Argument 1 passed to Nyholm\Psr7\Stream::create() must be of the type string, bool given, called in \vendor\nyholm\psr7\src\Factory\StreamFactory.php on line 26 and defined in \vendor\nyholm\psr7\src\Stream.php:80
Stack trace:
#0 \vendor\nyholm\psr7\src\Factory\StreamFactory.php(26): Nyholm\Psr7\Stream::create(true)
#1 \vendor\php-http\multipart-stream-builder\src\MultipartStreamBuilder.php(61): Nyholm\Psr7\Factory\StreamFactory->createStream(true)
#2 \vendor\mailgun\mailgun-php\src\Mailgun\RequestBuilder.php(62): Http\Message\MultipartStream\MultipartStreamBuilder->addResource('o:require-tls', true, Array)
#3 \vendor\mailgun\mailgun-php\src\Mailgun\Api\HttpApi.php(160): Mailgun\RequestBuilder->create('POST', '/v3/...', Array, Array)
#4 \vendor\mailgun\mailgun-php\src\Mailgun\Api\Message.php(62): Mailgun\Api\HttpApi->httpPostRaw('/v3/...', Array)
#5 \test\mailgun.php(13): M in \vendor\nyholm\psr7\src\Stream.php on line 80
```

Workaround:
```php
$mg->messages()->send(MailgunDomain, [
	'from' => From,
	'to' => To,
	'subject' => 'Test',
	'html' => 'Hello world',
	//'o:require-tls' => true,
]);
```

Relevant composer.json:
```json
{
    "config": {
        "platform": {
            "php": "7.0"
        }
    },
    "require": {
        "react/promise": "^2.5",
	"mailgun/mailgun-php": "^2.8",
	"kriswallsmith/buzz": "^0.16.1",
	"nyholm/psr7": "^0.2.3",
	"php-http/guzzle6-adapter": "^1.1",
	"php-http/message": "^1.7"
    }
}
```

**Comment by DavidGarciaCat** [comment]
Hi @truefusion 

I can see the code is based on the example we have available in the README file, so it should be working. Additional flags can be passed to the `send()` method as described in the documentation (we don't process them differently).

To be honest, I never used the `o:require-tls` flag, so maybe another community member can bring some input if they have used it? Alternatively, I will need to invest some time (probably this month, but not today) investigating.

Cheers,

**Comment by Nyholm** [comment]
The `o:*` options are sent as headers. Headers must be strings. 

```diff
 $mg = Mailgun::create(MailGunKey);
 
 $mg->messages()->send(MailgunDomain, [
	'from' => From,
	'to' => To,
	'subject' => 'Test',
	'html' => 'Hello world',
-	'o:require-tls' => true,
+	'o:require-tls' => 'true',
 ]);
```

**Comment by DavidGarciaCat** [comment]
Closing this issue due to inactivity. Also, Nyholm's example should fix the problem.
