### ISSUE TITLE
Uncaught InvalidArgumentException

### ISSUE THREAD

**Issue by kirilcvetkov** [mailgun/mailgun-php#823]
```
Array
(
    [type] => 1
    [message] => Uncaught InvalidArgumentException: First argument to "Http\Message\MultipartStream\MultipartStreamBuilder::createStream()" must be a string, resource or StreamInterface. in /.../vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php:353
Stack trace:
#0 /.../vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php(106): Http\Message\MultipartStream\MultipartStreamBuilder->createStream(true)
#1 /.../vendor/mailgun/mailgun-php/src/HttpClient/RequestBuilder.php(68): Http\Message\MultipartStream\MultipartStreamBuilder->addResource('o:tracking', true, Array)
#2 /.../vendor/mailgun/mailgun-php/src/Api/HttpApi.php(158): Mailgun\HttpClient\RequestBuilder->create('POST', '/v3/domain....', Array, Array)
#3 /.../vendor/mailgun/mailgun-php/src/Api/Message.php(60): Mailgun\Api\HttpApi->httpPostRaw('/v3/domain....', Array)
#4 /.../test.php(25): Mailgun\Api\Message->send('domain.com', Array)
#5 {main}
  thrown
    [file] => /.../vendor/php-http/multipart-stream-builder/src/MultipartStreamBuilder.php
    [line] => 353
)
```

Installed version in composer.json: "mailgun/mailgun-php": "^3.5",

Test code:

use Mailgun\Mailgun;

```
$parameters = [
    'from' => "John Doe <John.doe@email.com>",
    'to' => "someone@else.com",
    'subject' => "This is a test",
    'text' => "This is also a test on the text field",
    'html' => "<html><body>And <b>this</b> is a test on the hmtl field</body></html>",
    'o:tracking' => true,
];

$mg = Mailgun::create('key');

$result = $mg->messages()->send('domain', $parameters);

```

The issue is that the 'o:tracking' parameter has a boolean value. When I changed it to a string with the number 1, the error went away.

`'o:tracking' => '1',
`

I'm uncertain that this is an actual issue but I thought it might help.

**Comment by oleksandr-mykhailenko** [comment]
Hello @kirilcvetkov 
So technically it's not a bug with API itself, because in the API doc it says that we accept strings with next values
![image](https://user-images.githubusercontent.com/9269550/180611689-b857aee2-c962-4ab3-8325-26f00d4a234c.png)

But according to the code, it's bug because we need to prevent such possible case.
So anyway the library was update and new release is here - https://github.com/mailgun/mailgun-php/releases/tag/v3.5.2

Thank you for your message and enjoy your coding.
Have a good day
